name: Deploy

on:
  push:
    branches:
      - master
  pull_request:

env:
  env_name: ${{ github.ref != 'refs/heads/master' && format('pr-{0}', github.event.number) || 'prod' }}
  cf_name: ${{ github.ref != 'refs/heads/master' && format('pr-{0}', github.event.number) || 'main' }}
  env_url: ${{ github.ref != 'refs/heads/master' && format('https://pr-{0}.{1}.pages.dev', github.event.number, 'containerflare') || 'https://cfcr.dev' }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    environment:
      name: ${{ github.ref != 'refs/heads/master' && format('pr-{0}', github.event.number) || 'prod' }}
      url: ${{ github.ref != 'refs/heads/master' && format('https://pr-{0}.{1}.pages.dev', github.event.number, 'containerflare') || 'https://cfcr.dev' }}
    if: github.event.pull_request.merged != true && github.event.pull_request.closed != true
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Initialize npm
        run: npm ci

      - name: Initialize npm
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: containerflare
          directory: ./dist
          branch: ${{ env.cf_name }}
        id: publish
