name: Deploy

on:
  push:
    branches:
      - master
  pull_request:

env:
  isPR: github.ref != 'refs/heads/master'
  env_name: ${{ github.ref != 'refs/heads/master' && 'pr-${{ github.event.number }}' || 'prod' }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    environment:
      name: env.env_name
      url: ${{ env.isPR && steps.publish.outputs.url || 'https://cfcr.dev' }}
    env:
      cf_name: ${{ ${{ env.isPR }} && env.env_name || 'testmain' }}
      env_url: ${{ ${{ env.isPR }} && steps.publish.outputs.url || 'https://cfcr.dev' }}
    name: Deploy to Cloudflare Pages
    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: env.env_name

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Initialize npm
        run: npm ci

      - name: Initialize npm
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: containerflare
          directory: ./dist
          branch: env.cf_name
        id: publish

      - name: Outputs
        run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: ${{ steps.publish.outputs.environment }}"
          echo "Alias: ${{ steps.publish.outputs.alias }}"

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: env.env_name
          env_url: env.env_url
          debug: true

      - name: Find PR comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: "github-actions[bot]"
          body-includes: "preview of this pull request"

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            A preview of this pull request is ready!
            See it at ${{ env_url }}
            View the deploy log at https://github.com/MNThomson/containerflare/actions/runs/${{ github.run_id}}
          edit-mode: replace

      # - name: Remove deployment
      #   uses: bobheadxi/deployments@v1.3.0
      #   with:
      #     step: delete-env
      #     token: ${{ secrets.GH_TOKEN }}
      #     env: ${{ env.STORYBOOK_BRANCH_SLUG }}
