name: Pull Request Cleanup

on:
  pull_request_target:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Deactivate deployment
        uses: bobheadxi/deployments@v1
        with:
          step: deactivate-env
          token: ${{ github.token }}
          env: pr-${{ github.event.number }}
          desc: Deployment was pruned
