name: Pull Request Cleanup

on:
  pull_request_target:
    types:
      - closed

jobs:
  cleanup:
    permissions:
      deployments: write
    name: Delete environment
    runs-on: ubuntu-latest
    steps:
      - name: Delete deployment
        uses: bobheadxi/deployments@v1
        with:
          step: delete-env
          token: ${{ github.token }}
          env: pr-${{ github.event.number }}
          desc: Deployment was pruned
